### ISSUE TITLE
把博客迁移到 Next.js 

### ISSUE THREAD

**Issue by yuxino** [yuxino/blog#105]
## 动机

博客年久失修,冗余代码也比较多,还用了个没什么卵用的antd增大了体积。最近在用now,于是打算把博客迁到now上面去，不再是`serverless`的了, 但还是是免费的 ... 毕竟用了now。的。于是我选了next.js。这里记录一下迁移的时候遇到的一些东西和问题。

## scss

新的版本打算用回scss了,因为`styled-components`很久没用了,`css in js`也没感觉那么香了,于是回坑。官方其实不太推荐全局`scss`的。但是总是要用的啊。于是就安装了`scss`。毕竟是开箱即用的。没有过多的阻碍,安`scss`就是这么的简单。

### 如何让scss在next里面跑起来

`next.js` 现在的版本是支持`scs`s的，不需要装依赖了，直接 `yarn add sass`就行了。next默认是`css module`,全局的只能丢`_app.tsx`里,否则都是以`.modules`命名。嘛,有好有坏。

### 如何全局引用

创建一个`pages/_app.tsx`，在里面引用就好了。

## 定义 api

可以把`api.ts`丢进`pages/api`里面,比如`pages/api/random`。

``` ts
export default (req, res) => {
  res.status(200).json({
    quote: 'Write tests, not too many, mostly integration',
    author: 'Guillermo Rauch'
  });
};
```

这样在路由访问`api/randomQuote`的时候就会返回上面写的值。

## 网站图标配置

这个也很容易，因为`next`允许我们自定义`document`。就像spa应用里的`index.html`一样。创建一个`pages/_document.tsx`。然后把代码贴上去就好了。

``` tsx
import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    return (
      <Html>
        <Head>
          <link rel="shortcut icon" href="/favicon.ico" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

`favicon.ico`那段就是图标了，把图标丢在`public`文件夹里。因为`public`文件夹是拿来托管静态文件的。

## 自定义 layout

还是用到了那个`pages/_app.tsx`。因为直接写在其他的`pages`组件里面会导致布局被重选染的问题，我们并不需要老是渲染，所以拿出来。而且这样我们能更加容易的控制布局(比如改变navbar的透明度之类的)。

## 自定义加载 loading

我用的是`Nprogress`魔改了几个样式，装好以后，我就在`app.tsx`监听这仨函数，然后就好了。

``` tsx
import NProgress from "nprogress";
import Router from "next/router";

Router.events.on("routeChangeStart", NProgress.start);
Router.events.on("routeChangeComplete", NProgress.done);
Router.events.on("routeChangeError", NProgress.done);
```

## 总结

Hook用的挺爽的，Next的坑算是比较少的。体验不错。

**Comment by Muzm** [comment]
尬桑你博客看不到东西啦

**Comment by Muzm** [comment]
![image](https://user-images.githubusercontent.com/18257790/80055065-5995f100-8553-11ea-9c66-9a5079c96834.png)

**Comment by yuxino** [comment]
@Muzm 已经不是这样的了 在now那里 yuxino.now.sh
