### ISSUE TITLE
Java Nested Classes

### ISSUE THREAD

**Issue by yuxino** [yuxino/blog#27]
Nested Classes is a very important concept in Java . This note Contains the main parts:

- Introduce Nested Classes
- Inner Class Example
- Local Classes
- Anonymous Classes
- Lambda in Java
  - Method References

Reference from [Java Tutorials](http://docs.oracle.com/javase/tutorial/java/javaOO/nested.html).

**Comment by Nbsaw** [comment]
The Java programming language allows you to define a class within another class. Such a class is called a nested class and is illustrated here:

class OuterClass {
    ...
    class NestedClass {
        ...
    }
}
Terminology: Nested classes are divided into two categories: static and non-static. Nested classes that are declared static are called static nested classes. Non-static nested classes are called inner classes.
class OuterClass {
    ...
    static class StaticNestedClass {
        ...
    }
    class InnerClass {
        ...
    }
}
A nested class is a member of its enclosing class. Non-static nested classes (inner classes) have access to other members of the enclosing class, even if they are declared private. Static nested classes do not have access to other members of the enclosing class. As a member of the OuterClass, a nested class can be declared private, public, protected, or package private. (Recall that outer classes can only be declared public or package private.)

Why Use Nested Classes?

**Comment by Nbsaw** [comment]
## Inner Class Example
To see an inner class in use, first consider an array. In the following example, you create an array, fill it with integer values, and then output only values of even indices of the array in ascending order.

**Comment by Nbsaw** [comment]
## Local Classes
Local classes are classes that are defined in a `block`, which is a group of zero or more statements between balanced braces. You typically find local classes defined in the body of a method.

**Comment by Nbsaw** [comment]
## Anonymous Classes

Anonymous classes enable you to make your code more concise. **They enable you to declare and instantiate a class at the same time.**

**Comment by Nbsaw** [comment]
## Lambda Expressions
The previous section, Anonymous Classes, shows you how to implement a base class without giving it a name. Although this is often more concise than a named class, for classes with only one method, even an anonymous class seems a bit excessive and cumbersome. Lambda expressions let you express instances of single-method classes more compactly.

**Comment by Nbsaw** [comment]
## Method References

You use lambda expressions to create anonymous methods. Sometimes, however, a lambda expression does nothing but call an existing method. In those cases, it's often clearer to refer to the existing method by name. Method references enable you to do this; they are compact, easy-to-read lambda expressions for methods that already have a name.

Consider again the [Person](http://docs.oracle.com/javase/tutorial/java/javaOO/examples/Person.java) class discussed in the section Lambda Expressions:

``` java
public class Person {

    public enum Sex {
        MALE, FEMALE
    }

    String name;
    LocalDate birthday;
    Sex gender;
    String emailAddress;

    public int getAge() {
        // ...
    }
    
    public Calendar getBirthday() {
        return birthday;
    }    

    public static int compareByAge(Person a, Person b) {
        return a.birthday.compareTo(b.birthday);
    }}
```

Suppose that the members of your social networking application are contained in an array, and you want to sort the array by age. You could use the following code (find the code excerpts described in this section in the example MethodReferencesTest):

``` java
List<Person> roster = createRoster();
Person[] rosterAsArray = roster.toArray(new Person[roster.size()]);

class PersonAgeComparator implements Comparator<Person> {
    public int compare(Person a, Person b) {
        return a.getBirthday().compareTo(b.getBirthday());
    }
}
        
Arrays.sort(rosterAsArray, new PersonAgeComparator());
```

**Comment by Nbsaw** [comment]
Done :)
