### ISSUE TITLE
React render prop 和 Vue slot-scope

### ISSUE THREAD

**Issue by yuxino** [yuxino/blog#53]
之前有看过`render prop`或者`render children`的文章。第一次看是看尤雨溪推特发的那条。楼下有人问在vue里面有类似`render prop`这样的操作吗? 尤雨溪给的答案是`slot-scope`。 当时也看不懂他们在聊啥，也不是很理解`render prop`的概念，文章也只是虽翻遍了两下就close了。只记得作者好像是个光头，也叫Mj,不过不是King of Pop。

之前文章没认真看也不知道场景。有一天在搜不知道什么的时候搜到了一个叫做react-media的库。看了一下Usage被惊艳到了，但是又感觉似曾相识。才想起来是之前看的文章，再看这个库的作者就是那个光头,mj 。

我们先看一下库的用法吧。

``` jsx
import React from "react";
import Media from "react-media";

class App extends React.Component {
  render() {
    return (
      <div>
        <Media query="(max-width: 599px)">
          {matches =>
            matches ? (
              <p>The document is less than 600px wide.</p>
            ) : (
              <p>The document is at least 600px wide.</p>
            )
          }
        </Media>
      </div>
    );
  }
}
```

通过`matches `的true/false来决定显示哪一种视图。代码真的非常清晰。与以往的jsx写法不一样。这里的children是直接传的一个function过去。这就是`render children`。还有一种是`render prop`。

``` jsx
import React from "react";
import Media from "react-media";

class App extends React.Component {
  render() {
    return (
      <div>
        <Media
          query="(max-width: 599px)"
          render={() => <p>The document is less than 600px wide.</p>}
        />
      </div>
    );
  }
}
```

它们基本上没有差异只是叫法上有略微的差异。本质上children也是个prop。所以`render children`也算是`render prop`。

`render prop`在社区慢慢的变的热门了起来。React 16.3的新的Context Api就用到了这一特性。通过`Provider`和`Consume`配合使用可以替代一些Redux的工作。[文档](https://reactjs.org/docs/context.html)在这里。React官方文档也有[render-props](https://reactjs.org/docs/render-props.html)的介绍。写的非常的清晰。

我在这里用`react-media`描述一下工作原理。主要我们看render部分的[代码](https://github.com/ReactTraining/react-media/blob/master/modules/Media.js#L54-L67)

``` jsx
render() {
const { children, render } = this.props;
const { matches } = this.state;

return render
  ? matches ? render() : null
  : children
    ? typeof children === "function"
      ? children(matches)
      : !Array.isArray(children) || children.length // Preact defaults to empty children array
        ? matches ? React.Children.only(children) : null
        : null
    : null;
}
```

holy shit，这段三元。我整理一下。顺便发个[PR](https://github.com/ReactTraining/react-media/pull/90)

``` jsx
render() {
  const { children, render } = this.props;
  const { matches } = this.state;
  if (render && matches) {
    return render ()
  }
  else if (children && typeof children === "function") {
    return children(matches)
  }
  else if ((!Array.isArray(children) || children.length) && matches) {
    return React.Children.only(children)
  }
  return null
}
```

原理就是将prop作为functional component。把父(React-Media)组件的状态传下去。**`render prop`相较于之前的`HOC`会更加的灵活和易懂。并且能做到HOC能做到的所有事情。并且不会有`HOC`的缺点。**比如说:

1. prop的命名冲突，如果两个`HOC`的prop的参数名一样会导致前者的prop被覆盖掉。并且React不会告诉你被覆盖了。**如果使用了`render prop`，不会自动合并参数，所以也不会存在参数被覆盖的问题。**

2. 我们很难知道是哪个HOC组件提供了哪些状态作为prop。**如果使用了`render prop`我们可以直接看出哪些参数来自哪个组件。**

## Vue-slot scope

跟`render prop`有异曲同工之妙，可能是社区的共识。只需要在`slot`上bind一个值就可以直接在子组件使用`slot-scope`获取到然后使用。

## 参考资料

- [Mj的文章](https://cdb.reacttraining.com/use-a-render-prop-50de598f11ce)

**Comment by Hazlank** [comment]
![](https://user-images.githubusercontent.com/12481935/38940195-2ec46910-435c-11e8-9516-ce5276166389.png)

**Comment by Charlotte777** [comment]
好多光头
