### ISSUE TITLE
Typescript 动态枚举类型 (或者叫做限定类型)

### ISSUE THREAD

**Issue by yuxino** [yuxino/blog#95]
指定类型的动态字符串枚举类型 (其实我也不知道叫不叫这个，口胡的)

⚠️ TLDR; 叙述过程会很长，循环渐进的告诉你我的思路。如果你并不关心我的思路可以直接看答案。

回归正题。我们来探讨这个东西的意义何在。

比如你有一个组件`Select`吧。他是一个下拉组件。

![image](https://user-images.githubusercontent.com/12481935/61298108-35f98980-a810-11e9-8415-d8e9f1f07533.png)

下拉组件大概长这个样子。截的图是 antd 的下拉组件。

那么我们定义出两个 props。

- set 它是一组 string 类型的集合。Select 会通过循环把它变成下拉选项。
- defaultValue  它是 set 中的一个值。不允许是 set 以外的值。在这个截图里这个值就是`Lucy`

我们期待有下面这样的静态检查。 而不是运行的时候告诉我`Luxy`并不是一个有效的默认值。

``` html
// 这一个不会报错
<Select set={["Jack", "Lucy", "yiminghe"]} defaultValue={"Lucy"} />

// 这一个会报错。因为不是lucy，而是luxy
<Select set={["Jack", "Lucy", "yiminghe"]} defaultValue={"Luxy"} />
```

首先 `set` 是 一个 string 数组。那么我们可以定义为 `string[]`。然后 `defaultValue`会是这个 `set`中的一员。

但是知道这玩意没什么卵用。`defaultValue 和 `set` 无法关联起来。怎么表达出 `defaultValue`是`set`中的一员是个问题。

**要想知道这个怎么弄我们想了解一下一个特殊的语法`[number]`。这个语法对数组有效表示类型需要是数组中的其中一个的值。 看下面这个例子，`defaultValue`不是`a`就是`1`。其他的值通不过。**

![image](https://user-images.githubusercontent.com/12481935/61306391-1ae24600-a81f-11e9-9c6f-c6c9ccaa70d3.png)

我们先想出第一个可能的样子。`set`是`string[]`, `defaultValue`是`set`的一员、emmmmm，很显然这个跑不通, `set` 不是一个类型呀。那可咋办。

![image](https://user-images.githubusercontent.com/12481935/61306182-b7f0af00-a81e-11e9-98c5-b66058971cf7.png)

然后你想了个办法。那把 `set` 变成一个类型不就完事了。

![image](https://user-images.githubusercontent.com/12481935/61306123-98f21d00-a81e-11e9-8bbb-99d03e8c1fb4.png)

ok,ok 很接近但是还是不对。因为这里表达的意思是任何一个`string`类型都可以。那么问题来了，我们有办法限定类型吗。

限定类型那不就是哦泛型吗 ... 来复习一下泛型。准确的说认识一下泛型数组。

![image](https://user-images.githubusercontent.com/12481935/61306754-b1af0280-a81f-11e9-883d-f761136d84ef.png)

我们可以看见泛型会被数组的第一个接收到的值限定死类型。所以第二个`Select`组件被检查出是有问题的，除非传一个数字作为参数。

我们知道泛型可以通过`extends`集成类型的。这样我们就有办法让泛型是某个固定的类型或者是**它的子类**。我们稍微结合一下前面学到的 `[number]`, 有了如下的代码。

![image](https://user-images.githubusercontent.com/12481935/61307056-339f2b80-a820-11e9-8074-9f5b9be43df3.png)

emmmm。 这个肯定也不符合我们想要的，因为他和之前写的`type set = string[]`几乎是没有差别的。

斯国一。这样就只能传字符串和**字符串的子类型**了。但是这有个锤子用。。不不不 这有用。我们稍微移动一下中括号。

![image](https://user-images.githubusercontent.com/12481935/61308340-a7423800-a822-11e9-92fb-12c8c1173c16.png)

变成了这个样子。这说明在ts里泛型是可以继承自数组的。也就是泛型数组 (其他语言好像不可以的亚子)。

但是就算是这样还是没什么卵用。无法阻止我们乱传`defaultValue`。

这时候再给你灌输一点概念。ts 的数组是可以继承的。

![image](https://user-images.githubusercontent.com/12481935/61310275-8bd92c00-a826-11e9-86eb-33fcfac5ec1a.png)

被继承的数组会被要求有数组里的所有值。并且我们无法给他添加其他的新的值，新的数组的项。也就是说这个被继承的数组是一个**被限定值类型的数组**。

我们稍微改造一下我们之前写的泛型。把它变成了这样

![image](https://user-images.githubusercontent.com/12481935/61310594-30f40480-a827-11e9-82c9-80c7ff397a84.png)

诶，这时候只能输入`set`限定的类型了。已经达到了我们的期望。但是为啥可以达到呢。因为是这样的。

虽然V是继承自`string`，但是并不是所有的`string`类型都可以作为参数传给`defaultValue`的。必须在`V[]`的范围内的`string`才可以。

这样一来就打到我们的目的了。如果觉得只限制`string`类型太死了。你甚至可以这样。

![image](https://user-images.githubusercontent.com/12481935/61340667-df269b00-a875-11e9-84ec-39d4d7eeab20.png)

**Comment by xTaTnT** [comment]
看了这篇文章学习到不少 ts 知识，有个小问题，实际情况中，set 很大概率是长这样的: [{ value: 'xxx', label: 'xxx'}]，而不是简单的字符串。这种情况下该如何拿 set 中每一项 value 的值，来给 defaultValue 做提示呢？

**Comment by yuxino** [comment]
@xTaTnT 有办法拿到 等我过阵子有空了写给你看

**Comment by He110te4m** [comment]
用 as const 断言就行了，
```typescript
const SET = [ 'a', 'b' ] as const
type SelectValue = (typeof SET)[number];
let test: SelectValue = 'c' // error
```

**Comment by yuxino** [comment]
@He110te4m yes。 这好久之前的了
